DROP TABLE promos;
DROP TABLE promo_schedule;

CREATE TABLE IF NOT EXISTS `promos` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(50) NOT NULL DEFAULT '0',
  `DESCRIPTION` varchar(1000) DEFAULT '0',
  `VALID_FROM` date NOT NULL,
  `VALID_TO` date NOT NULL,
  `SALES_PERIOD_FROM` date NOT NULL,
  `SALES_PERIOD_TO` date NOT NULL,
  `PRICE` decimal(10,2) NOT NULL DEFAULT '0.00',
  `UPDATED_BY` bigint(20) NOT NULL DEFAULT '0',
  `CREATED_BY` bigint(20) NOT NULL DEFAULT '0',
  `UPDATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `promo_schedule` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `PROMO_ID` bigint(20) unsigned DEFAULT '0',
  `USER_ID` bigint(20) unsigned DEFAULT '0',
  `BOOKING_STATUS` varchar(50) DEFAULT 'PENDING',
  `UPDATED_BY` bigint(20) unsigned DEFAULT '0',
  `CREATED_BY` bigint(20) unsigned DEFAULT '0',
  `UPDATED_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CREATED_DATE` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;