INSERT INTO CATEGORY (NAME) VALUES ('Class');
INSERT INTO CATEGORY (NAME) VALUES ('Airlines');
INSERT INTO CATEGORY (NAME) VALUES ('Vehicle Type');
INSERT INTO CATEGORY (NAME) VALUES ('User Type');
INSERT INTO CATEGORY (NAME) VALUES ('Booking Status');
INSERT INTO CATEGORY (NAME) VALUES ('Destination');
INSERT INTO CATEGORY (NAME) VALUES ('Ticket Type');
INSERT INTO CATEGORY (NAME) VALUES ('Hotel');

INSERT INTO LOOKUPS (CATEGORY_ID, VALUE) VALUES ((SELECT ID FROM CATEGORY WHERE NAME = 'User Type'), 'CUSTOMER');
INSERT INTO LOOKUPS (CATEGORY_ID, VALUE) VALUES ((SELECT ID FROM CATEGORY WHERE NAME = 'User Type'), 'ADMINISTRATOR');